KillEntityOnDisable: true
NoClickInventory: true
BlockProtect:
  world:
    NoDoorBreak: true
    NoLeavesDecay: true
    NoNotePlay: true
    NoBlockGrow: true
    NoBlockMelt: true
    NoBlockExp: true
    NoBlockBreakByFire: true
    NoDispense: true
    NoPortalTeleport: true
    NoTreeGrow: true
    NoPortalCreate: true
    NoWeather: true
EntityProtect:
  world:
    EntityVoidSpawn: true
    NoDamage: true
PlayerProtect
  world:
    NoFood: true
    VoidPlayerSpawn: true
Spawn:
  world:
    NoThrowEgg: true
    NoSlimeSplit: false
    NoSpawner: true
    NoBlockIgnite: true
  city:
    NoThrowEgg: true
    NoSlimeSplit: false
    NoSpawner: true
Damage:
  world:
    NoCactus: true
    NoLava: true
    NoExplosion: true
    NoFall: true
    NoDrowning: true
    NoLightning: true
    NoFire: true
    NoWall: true
Open:
  world:
    anvil: false
    beacon: false
    brewing: false
    chest: false
    crafting: false
    dispenser: false
    dropper: false
    enchanting: false
    enderchest: true
    hopper: false
    furnace: false
    workbench: false
  city:
    anvil: false
    beacon: false
    brewing: false
    chest: false
    crafting: false
    dispenser: false
    dropper: false
    enchanting: false
    enderchest: false
    hopper: false
    furnace: false
    workbench: false
BoardCase:
  Enable: false
  Tick: 1200
  Message: 'KokiCraft<材质绘画>活动可参赛的材质:USP(原骨头),水枪(原水桶),无重力装置(原绿宝石),豌豆加农炮(原火焰弹),恶魂炮(原花盆),针筒(原地狱疣),奖励包括USP或各种不掉落RMB枪支.详情请加群:63733819并查看群公告'
worlds:
  city:
    pickup:
    - '355'
    - '54'
    - '263'
    - '263:1'
    - '175'
    - '371'
    - '259'
    - '76'
    - '407'
    - '398'
    - '288'
    - '378'
    - '262'
    - '419'
    - '418'
    - '280'
    - '417'
    - '255'
    - '369'
    - '385'
    - '326'
    - '388'
    - '390'
    - '276'
    - '372'
    - '279'
    - '293'
    - '277'
    - '278'
    - '342'
    - '289'
    - '352'
    item-drop:
    - '355'
    - '263'
    - '263:1'
    - '175'
    - '371'
    - '259'
    - '76'
    - '407'
    - '398'
    - '288'
    - '378'
    - '262'
    - '419'
    - '418'
    - '280'
    - '417'
    - '255'
    - '369'
    - '385'
    - '326'
    - '388'
    - '390'
    - '276'
    - '372'
    - '279'
    - '293'
    - '277'
    - '278'
    - '342'
    - '289'
    - '352'
    disable-all-drops: false
    disable-all-pickup: false
  world:
    pickup:
    - '355'
    - '54'
    - '263'
    - '263:1'
    - '175'
    - '371'
    - '259'
    - '76'
    - '407'
    - '398'
    - '288'
    - '378'
    - '262'
    - '419'
    - '418'
    - '280'
    - '417'
    - '255'
    - '369'
    - '385'
    - '326'
    - '388'
    - '390'
    - '276'
    - '372'
    - '279'
    - '293'
    - '277'
    - '278'
    - '342'
    - '289'
    - '352'
    item-drop:
    - '355'
    - '263'
    - '263:1'
    - '175'
    - '371'
    - '259'
    - '76'
    - '407'
    - '398'
    - '288'
    - '378'
    - '262'
    - '419'
    - '418'
    - '280'
    - '417'
    - '255'
    - '369'
    - '385'
    - '326'
    - '388'
    - '390'
    - '276'
    - '372'
    - '279'
    - '293'
    - '277'
    - '278'
    - '342'
    - '289'
    - '352'
    disable-all-drops: false
    disable-all-pickup: false

JoinTeleport:
  Enable: false
  World: world
  X: 0
  Y: 0
  Z: 0
  Pitch: 0
  Yaw: 0

BlockNoInteract:
#蛋糕
 - '92'
#石头按钮
# - '77'
#木头按钮
# - '143'
#栅栏门
# - '107'
#陷阱门
# - '96'
#木门
# - '46'
#中续器
 - '356'
#比较器
 - '404'
#花盆
 - '390'
#床
 - '355'
#唱片机
 - '84'
#传送门框架
 - '120'
#拉杆
# - '96'
#炼药锅
 - '123'