name: GameCore
main: com.kokicraft.GameCore.Main
version: 1.1.0
description: GameCore.
author: Koke_Cacao
commands:
   core:
      description: Reload config.
      permission: core.reload
      usage: /core reload